name: Reusable Workflows

on:  
  push:
  workflow_dispatch:

jobs:

  reuse_workflow: 
    uses: lfraile-dotnet-2022-workshop/.github/reusable-workflow/base-workflow.yml@main
    with:
       netcore_version: 3.1.402
    secrets:
       token: demo
