name: Reusable Workflows

on:  
  push:
  workflow_dispatch:

jobs:

  reuse_workflow: 
    uses: ./.github/workflows/base-reusable.yml
    with:
       netcore_version: 3.1.402
    secrets:
       token: demo
