name: Reusable Workflows

on:  
  push:
  workflow_dispatch:

jobs:
  reuse_workflow: 
    uses: lfraile-dotnet-2022-workshop/shared-workflows/workflows/reusable-workflow.yml@main
    with:
       netcore_version: 3.1.402
    secrets:
       token: demo
